/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author LUCYLEONOR
 */
import clases.*;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Fraccionario f1, f2, f3 = null;
    public Principal() {
        initComponents();
        txtNumerador1.requestFocusInWindow();
        cmdNumeroMixto.setEnabled(false);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNumerador1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtDenominador1 = new javax.swing.JTextField();
        txtNumerador2 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtDenominador2 = new javax.swing.JTextField();
        txtNumerador3 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtDenominador3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbOp = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        cmdCalcular = new javax.swing.JButton();
        cmdNumeroMixto = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMixtoCoc = new javax.swing.JTextField();
        txtMixtoMod = new javax.swing.JTextField();
        txtMixtoDenominador = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        cmdFraccionPropia = new javax.swing.JButton();
        cmdFraccionImpropia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNumerador1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtNumerador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 60, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 60, 10));

        txtDenominador1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtDenominador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 60, -1));

        txtNumerador2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtNumerador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 60, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 60, 10));

        txtDenominador2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtDenominador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 60, -1));

        txtNumerador3.setEditable(false);
        txtNumerador3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtNumerador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 60, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 60, 10));

        txtDenominador3.setEditable(false);
        txtDenominador3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtDenominador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 60, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("=");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 20, -1));

        cmbOp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmbOp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suma", "Resta", "Multiplicación", "División" }));
        cmbOp.setAutoscrolls(true);
        jPanel1.add(cmbOp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 90, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Options", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel2.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, -1));

        cmdNumeroMixto.setText("Número Mixto");
        cmdNumeroMixto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNumeroMixtoActionPerformed(evt);
            }
        });
        jPanel2.add(cmdNumeroMixto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, -1));

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 110, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 130, 160));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Fraccionarios");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabel3.setText("-------");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 30, 20));

        txtMixtoCoc.setEditable(false);
        txtMixtoCoc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtMixtoCoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 30, -1));

        txtMixtoMod.setEditable(false);
        txtMixtoMod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtMixtoMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 40, -1));

        txtMixtoDenominador.setEditable(false);
        txtMixtoDenominador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtMixtoDenominador, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 40, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 40, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText(">");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 10, 60));

        cmdFraccionPropia.setText("¿Que Es Una Fraccion Propia?");
        cmdFraccionPropia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFraccionPropiaActionPerformed(evt);
            }
        });
        jPanel1.add(cmdFraccionPropia, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 230, -1));

        cmdFraccionImpropia.setText("¿Que Es Una Fraccion Impropia?");
        cmdFraccionImpropia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFraccionImpropiaActionPerformed(evt);
            }
        });
        jPanel1.add(cmdFraccionImpropia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 240, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 230));

        setSize(new java.awt.Dimension(776, 270));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed

        int sw = 1;
        txtMixtoCoc.setText("");
        txtMixtoDenominador.setText("");
        txtMixtoMod.setText("");
        if (txtNumerador1.getText().trim().isEmpty() && txtNumerador2.getText().trim().isEmpty() && txtDenominador1.getText().trim().isEmpty() && txtDenominador2.getText().trim().isEmpty()) {
            Helper.mensaje(null, "Ingrese Los Datos", "Error", 2);
            txtNumerador1.requestFocusInWindow();

            txtNumerador1.setEnabled(true);
            txtNumerador2.setEnabled(true);
            txtDenominador1.setEnabled(true);
            txtDenominador2.setEnabled(true);

        } else if (txtNumerador1.getText().trim().isEmpty()) {
            Helper.mensaje(null, "Ingrese El Numerador 1", "Error", 2);
            txtNumerador1.requestFocusInWindow();

            txtNumerador1.setEnabled(true);
            txtNumerador2.setEnabled(true);
            txtDenominador1.setEnabled(true);
            txtDenominador2.setEnabled(true);

        } else if (txtNumerador2.getText().trim().isEmpty()) {
            Helper.mensaje(null, "Ingrese El Numerador 2", "Error", 2);
            txtNumerador2.requestFocusInWindow();

            txtNumerador1.setEnabled(true);
            txtNumerador2.setEnabled(true);
            txtDenominador1.setEnabled(true);
            txtDenominador2.setEnabled(true);

        } else if (txtDenominador1.getText().trim().isEmpty()) {
            Helper.mensaje(null, "Ingrese El Denominador 1", "Error", 2);
            txtDenominador1.requestFocusInWindow();

            txtNumerador1.setEnabled(true);
            txtNumerador2.setEnabled(true);
            txtDenominador1.setEnabled(true);
            txtDenominador2.setEnabled(true);

        } else if (txtDenominador2.getText().trim().isEmpty()) {
            Helper.mensaje(null, "Ingrese El Denominador 2", "Error", 2);
            txtDenominador2.requestFocusInWindow();

            txtNumerador1.setEnabled(true);
            txtNumerador2.setEnabled(true);
            txtDenominador1.setEnabled(true);
            txtDenominador2.setEnabled(true);

        } else {

            int op, n1 = 0, n2 = 0, n3 = 0, d1 = 0, d2 = 0, d3 = 0;
            op = cmbOp.getSelectedIndex();

            try{
            n1 = Integer.parseInt(txtNumerador1.getText());
            } catch (NumberFormatException e){
                Helper.mensaje(this, "Ingrese Un Numero Valido En El Numerador 1", "Error", 2);
                txtNumerador1.requestFocusInWindow();
                txtNumerador1.selectAll();
                sw = 0;
            }
            try {
                n2 = Integer.parseInt(txtDenominador1.getText());
            } catch (NumberFormatException e) {
                Helper.mensaje(this, "Ingrese Un Numero Valido En El Numerador 2", "Error", 2);
                txtDenominador1.requestFocusInWindow();
                txtDenominador1.selectAll();
                sw = 0;

            }
            try {
                d1 = Integer.parseInt(txtNumerador2.getText());
            } catch (NumberFormatException e) {
                Helper.mensaje(this, "Ingrese Un Numero Valido En El Denominador 1", "Error", 2);
                txtNumerador2.requestFocusInWindow();
                txtNumerador2.selectAll();
                sw = 0;

            }
            try {
                d2 = Integer.parseInt(txtDenominador2.getText());

            } catch (NumberFormatException e) {
                Helper.mensaje(this, "Ingrese Un Numero Valido En El Denominador 2", "Error", 2);
                txtDenominador2.requestFocusInWindow();
                txtDenominador2.selectAll();
                sw = 0;

            }

            if (sw == 1) {
                
            
            if (Integer.parseInt(txtDenominador1.getText()) == 0) {
                Helper.mensaje(this, "No Se Puede Dividir Por 0","Error",2);
                txtDenominador1.requestFocusInWindow();
                txtDenominador1.selectAll();
            }
            else if (Integer.parseInt(txtDenominador2.getText()) == 0) {
                Helper.mensaje(this, "No Se Puede Dividir Por 0","Error",2);
                txtDenominador2.requestFocusInWindow();
                txtDenominador2.selectAll();
            }
            else{
            
            
                f1 = new Fraccionario(n1, n2);
                f2 = new Fraccionario(d1, d2);

                switch (op) {
                    case 0:
                        f3 = f1.suma(f2);
                        break;
                    case 1:
                        f3 = f1.resta(f2);
                        break;
                    case 2:
                        f3 = f1.multiplicacion(f2);
                        break;
                    case 3:
                        f3 = f1.division(f2);
                        break;

                }
                txtNumerador3.setText("" + f3.getNumerador());
                txtDenominador3.setText("" + f3.getDenominador());
            
            } 
            cmdNumeroMixto.setEnabled(true);
            
        
        }
        }
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed

        txtNumerador1.setText("");
        txtNumerador2.setText("");
        txtNumerador3.setText("");
        txtDenominador1.setText("");
        txtDenominador2.setText("");
        txtDenominador3.setText("");
        txtMixtoCoc.setText("");
        txtMixtoDenominador.setText("");
        txtMixtoMod.setText("");
        cmdNumeroMixto.setEnabled(false);
        
        txtNumerador1.requestFocusInWindow();
        
        cmbOp.setSelectedIndex(0);

    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void cmdNumeroMixtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNumeroMixtoActionPerformed

        if (Integer.parseInt(txtNumerador3.getText()) < Integer.parseInt(txtDenominador3.getText())) {
            Helper.mensaje(null, "La Fraccion Debe Ser Impropia Para Pasarla A Mixto", "Error", 2);
            

        } else {

            f3.ConvertirMixto();

            txtMixtoMod.setText("" + f3.getNumerador());
            txtMixtoCoc.setText("" + f3.getDenominador());
            txtMixtoDenominador.setText(txtDenominador3.getText());
            cmdCalcular.setEnabled(true);
            cmdNumeroMixto.setEnabled(true);
            
        }

    }//GEN-LAST:event_cmdNumeroMixtoActionPerformed

    private void cmdFraccionImpropiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFraccionImpropiaActionPerformed

        Helper.mensaje(this, "Una Fraccion Impropia Es Aquella Que Su Numerador Es Mayor O Igual Que El Denominador.", "Informacion", 1);
    }//GEN-LAST:event_cmdFraccionImpropiaActionPerformed

    private void cmdFraccionPropiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFraccionPropiaActionPerformed
        Helper.mensaje(this, "Una fracción propia es una fracción donde el numerador (el número de arriba) es menor que el denominador (el número de abajo).", "Informacion", 1);
    }//GEN-LAST:event_cmdFraccionPropiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOp;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdFraccionImpropia;
    private javax.swing.JButton cmdFraccionPropia;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdNumeroMixto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField txtDenominador1;
    private javax.swing.JTextField txtDenominador2;
    private javax.swing.JTextField txtDenominador3;
    private javax.swing.JTextField txtMixtoCoc;
    private javax.swing.JTextField txtMixtoDenominador;
    private javax.swing.JTextField txtMixtoMod;
    private javax.swing.JTextField txtNumerador1;
    private javax.swing.JTextField txtNumerador2;
    private javax.swing.JTextField txtNumerador3;
    // End of variables declaration//GEN-END:variables
}
